# Generated by Django 5.1.3 on 2024-12-10 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_car_dimensions_drivetrain_engineinformation_metacar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='A document related to the auction, e.g., car history', upload_to='auction_documents/', verbose_name='Document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the document was uploaded', verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Auction Document',
                'verbose_name_plural': 'Auction Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='The image file', upload_to='images/', verbose_name='File')),
                ('description', models.TextField(blank=True, help_text='Optional description of the image', null=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the image was uploaded', verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the auction starts', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(help_text='The date when the auction ends', verbose_name='End Date')),
                ('likes', models.PositiveIntegerField(default=0, help_text='Number of likes received by the auction', verbose_name='Likes')),
                ('dislikes', models.PositiveIntegerField(default=0, help_text='Number of dislikes received by the auction', verbose_name='Dislikes')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of clicks on the auction', verbose_name='Clicks')),
                ('localization', models.CharField(help_text='Location of the car being sold', max_length=100, verbose_name='Localization')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Current status of the auction', max_length=15, verbose_name='Status')),
                ('type', models.CharField(choices=[('PRIVATE', 'Private'), ('BUSINESS', 'Business')], default='PRIVATE', help_text='Type of the auction: private or business', max_length=15, verbose_name='Type')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of views the auction has received', verbose_name='Views Count')),
                ('car', models.ForeignKey(help_text='The car being auctioned', on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='cars.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'ordering': ['-start_date'],
            },
        ),
    ]
