# Generated by Django 5.1.3 on 2024-12-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(help_text='The user who created the auction', on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='auctiondocument',
            name='auction',
            field=models.ForeignKey(help_text='The auction this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='auctions.auction', verbose_name='Auction'),
        ),
        migrations.AddField(
            model_name='auctionphoto',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='auctions.auction'),
        ),
    ]
