# Generated by Django 5.1.3 on 2024-12-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('vin_number', models.CharField(max_length=50, unique=True)),
                ('date_of_first_registration', models.DateField()),
                ('generation', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('year_of_production', models.IntegerField()),
                ('engine_capacity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('engine_power', models.PositiveIntegerField()),
                ('gear_box', models.CharField(max_length=50)),
                ('type_of_fuel', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('damage_condition', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
